// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/



package com.example.figuras.analizadores;

import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.*;
import java.io.Reader;

/*
Agregar la importacion del paquete
*/


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class MyLexer implements Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\3\1\1\0\2\1\22\0\1\1\7\0\1\2"+
    "\1\3\1\4\1\5\1\6\1\7\1\0\1\10\12\11"+
    "\47\0\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\0\1\21\1\22\1\0\1\23\1\24\1\25\1\26"+
    "\1\27\1\0\1\30\1\0\1\31\1\32\1\33\3\0"+
    "\1\34\u0185\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\12\1\45\0\1\13\1\14\13\0"+
    "\1\15\6\0\1\16\1\0\1\17\2\0\1\20\3\0"+
    "\1\21\1\0\1\22\4\0\1\23\1\0\1\24\4\0"+
    "\1\25\2\0\1\26\2\0\1\27\1\30\1\31\1\32"+
    "\1\33\2\0\1\34";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\35\0\35\0\35\0\35\0\35\0\35\0\35"+
    "\0\35\0\35\0\72\0\127\0\164\0\221\0\256\0\313"+
    "\0\350\0\u0105\0\u0122\0\u013f\0\u015c\0\u0179\0\u0196\0\u01b3"+
    "\0\u01d0\0\u01ed\0\u020a\0\u0227\0\u0244\0\u0261\0\u027e\0\u029b"+
    "\0\u02b8\0\u02d5\0\u02f2\0\u030f\0\u032c\0\u0349\0\u0366\0\u0383"+
    "\0\u03a0\0\u03bd\0\u03da\0\u03f7\0\u0414\0\u0431\0\u044e\0\u046b"+
    "\0\u0488\0\u04a5\0\u04c2\0\u04df\0\u04fc\0\u0519\0\u0536\0\u0553"+
    "\0\u0570\0\u058d\0\35\0\35\0\u05aa\0\u05c7\0\u05e4\0\u0601"+
    "\0\u061e\0\u063b\0\u0658\0\u0675\0\u0692\0\u06af\0\u06cc\0\35"+
    "\0\u06e9\0\u0706\0\u0723\0\u0740\0\u075d\0\u077a\0\35\0\u0797"+
    "\0\35\0\u07b4\0\u07d1\0\35\0\u07ee\0\u080b\0\u0828\0\35"+
    "\0\u0845\0\35\0\u0862\0\u087f\0\u089c\0\u08b9\0\35\0\u08d6"+
    "\0\35\0\u08f3\0\u0910\0\u092d\0\u094a\0\35\0\u0967\0\u0984"+
    "\0\35\0\u09a1\0\u09be\0\35\0\35\0\35\0\35\0\35"+
    "\0\u09db\0\u09f8\0\35";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\2\1\15\3\2\1\16\2\2"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\2\2\1\25"+
    "\1\2\46\0\1\13\47\0\1\26\1\27\6\0\1\30"+
    "\12\0\1\31\6\0\1\32\10\0\1\33\32\0\1\34"+
    "\25\0\1\35\41\0\1\36\20\0\1\37\3\0\1\40"+
    "\31\0\1\41\47\0\1\42\24\0\1\43\7\0\1\44"+
    "\24\0\1\45\30\0\1\46\43\0\1\47\7\0\1\50"+
    "\35\0\1\51\21\0\1\52\45\0\1\53\16\0\1\54"+
    "\15\0\1\55\16\0\1\56\47\0\1\57\37\0\1\60"+
    "\34\0\1\61\24\0\1\62\36\0\1\63\35\0\1\64"+
    "\25\0\1\65\42\0\1\66\42\0\1\67\34\0\1\70"+
    "\30\0\1\71\26\0\1\72\41\0\1\73\27\0\1\74"+
    "\32\0\1\75\35\0\1\76\52\0\1\77\20\0\1\100"+
    "\33\0\1\101\30\0\1\102\34\0\1\103\52\0\1\104"+
    "\22\0\1\105\37\0\1\106\44\0\1\107\31\0\1\110"+
    "\23\0\1\111\40\0\1\112\25\0\1\113\52\0\1\114"+
    "\36\0\1\115\32\0\1\116\16\0\1\117\43\0\1\120"+
    "\25\0\1\121\37\0\1\122\44\0\1\123\35\0\1\124"+
    "\37\0\1\125\23\0\1\126\26\0\1\127\40\0\1\130"+
    "\41\0\1\131\41\0\1\132\25\0\1\133\36\0\1\134"+
    "\23\0\1\135\36\0\1\136\46\0\1\137\30\0\1\140"+
    "\40\0\1\141\34\0\1\142\33\0\1\143\32\0\1\144"+
    "\37\0\1\145\34\0\1\146\23\0\1\147\31\0\1\150"+
    "\34\0\1\151\47\0\1\152\27\0\1\153\42\0\1\154"+
    "\36\0\1\155\32\0\1\156\36\0\1\157\32\0\1\160"+
    "\40\0\1\161\25\0\1\162\37\0\1\163\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2581];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\11\11\13\1\45\0\2\11\13\0\1\11\6\0"+
    "\1\11\1\0\1\11\2\0\1\11\3\0\1\11\1\0"+
    "\1\11\4\0\1\11\1\0\1\11\4\0\1\11\2\0"+
    "\1\11\2\0\5\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
	private List<ErroresC8> err;

public List<ErroresC8> getListaErroresLexicos(){
	return this.err;
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MyLexer(Reader in) {
      err = new ArrayList<>();
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return new Symbol(sym.EOF);
            }  // fall though
            case 116: break;
            default:
          { return new Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { err.add(new ErroresC8(yytext(),String.valueOf((yyline+1)),String.valueOf((yycolumn+1)),"Lexico","No se reconoce en el Lenguaje")) ;
            }
            // fall through
          case 29: break;
          case 2:
            { /*IGNORAR	*/
            }
            // fall through
          case 30: break;
          case 3:
            { return new Symbol(sym.PAR_ABIERTO,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 31: break;
          case 4:
            { return new Symbol(sym.PAR_CERRADO,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 32: break;
          case 5:
            { return new Symbol(sym.MULTIPLICACION,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 33: break;
          case 6:
            { return new Symbol(sym.SUMA,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 34: break;
          case 7:
            { return new Symbol(sym.COMA,yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 35: break;
          case 8:
            { return new Symbol(sym.RESTA,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 36: break;
          case 9:
            { return new Symbol(sym.DIVISION,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 37: break;
          case 10:
            { return new Symbol (sym.ENTERO, yyline+1,yycolumn+1,Integer.parseInt(yytext()));
            }
            // fall through
          case 38: break;
          case 11:
            { return new Symbol(sym.AZUL,yyline+1, yycolumn+1,("#1E90FF"));
            }
            // fall through
          case 39: break;
          case 12:
            { return new Symbol(sym.CAFE,yyline+1, yycolumn+1,("#F4A460"));
            }
            // fall through
          case 40: break;
          case 13:
            { return new Symbol(sym.ROJO,yyline+1, yycolumn+1,("#FF0000"));
            }
            // fall through
          case 41: break;
          case 14:
            { return new Symbol(sym.CURVA,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 42: break;
          case 15:
            { return new Symbol(sym.LINEA,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 43: break;
          case 16:
            { return new Symbol(sym.NEGRO,yyline+1, yycolumn+1,("#000000"));
            }
            // fall through
          case 44: break;
          case 17:
            { return new Symbol(sym.VERDE,yyline+1, yycolumn+1,("#008000"));
            }
            // fall through
          case 45: break;
          case 18:
            { return new Symbol(sym.ANIMAR,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 46: break;
          case 19:
            { return new Symbol(sym.MORADO,yyline+1, yycolumn+1,("#800080"));
            }
            // fall through
          case 47: break;
          case 20:
            { return new Symbol(sym.OBJETO,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 48: break;
          case 21:
            { return new Symbol(sym.CIRCULO,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 49: break;
          case 22:
            { return new Symbol(sym.NARANJA,yyline+1, yycolumn+1,("#FFA500"));
            }
            // fall through
          case 50: break;
          case 23:
            { return new Symbol(sym.AMARILLO,yyline+1, yycolumn+1,("#FFFF99"));
            }
            // fall through
          case 51: break;
          case 24:
            { return new Symbol(sym.ANTERIOR,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 52: break;
          case 25:
            { return new Symbol(sym.CUADRADO,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 53: break;
          case 26:
            { return new Symbol(sym.GRAFICAR,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 54: break;
          case 27:
            { return new Symbol(sym.POLIGONO,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 55: break;
          case 28:
            { return new Symbol(sym.RECTANGULO,yyline+1, yycolumn+1,(yytext()));
            }
            // fall through
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
